---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password-connect
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect.1password-connect.svc.cluster.local:8080"
      vaults:
        homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-token
            key: token
