---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'
set: [pipefail]
shopt: [globstar]

vars:
  ENCRYPTED_BACKEND: '{{ .TASKFILE_DIR }}/backend.sops.json'
  DECRYPTED_BACKEND: '{{ .TASKFILE_DIR }}/backend.json'

tasks:
  bootstrap:
    desc: Bootstrap Terraform config
    deps:
      - init
      - decrypt

  init:
    desc: Initialize terraform
    internal: true
    cmd: terraform -chdir='{{ .TASKFILE_DIR }}' init -backend-config='{{ .TASKFILE_DIR }}/backend.json'

  decrypt:
    internal: true
    deps:
      - decrypt-backend

  decrypt-backend:
    internal: true
    sources:
      - '{{ .ENCRYPTED_BACKEND }}'
    generates:
      - '{{ .DECRYPTED_BACKEND }}'
    cmds:
      - SOPS_AGE_KEY_FILE={{ .SOPS_AGE_KEY_FILE }} sops decrypt '{{ .ENCRYPTED_BACKEND }}' --output '{{ .DECRYPTED_BACKEND }}'


  plan:
    desc: terraform plan
    deps:
      - decrypt
    cmd: terraform -chdir='{{ .TASKFILE_DIR }}' plan

  apply:
    desc: terraform apply
    deps:
      - decrypt
    cmds:
      - terraform -chdir='{{ .TASKFILE_DIR }}' apply
