---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops
  interval: 5m
  path: "./infrastructure/external-secrets/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-operator
  interval: 5m
  path: "./infrastructure/external-secrets/resources"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

