---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'
set: [pipefail]
shopt: [globstar]

vars:
  SOPS_CONF_TEMPLATE: '{{ .TASKFILE_DIR }}/.sops.yaml.j2'

tasks:
  bootstrap:
    desc: Bootstrap SOPS keys
    deps:
      - setup-sops

  setup-sops:
    internal: true
    deps:
      - setup-age-key
    sources:
      - '{{ .SOPS_AGE_KEY_FILE }}'
    generates:
      - '{{ .ROOT_DIR }}/.sops.yaml'
    cmds:
      - minijinja-cli --define AGE_PUBLIC_KEY={{ .AGE_PUBLIC_KEY }} {{ .SOPS_CONF_TEMPLATE }} --output {{ .ROOT_DIR }}/.sops.yaml
    vars:
      AGE_PUBLIC_KEY:
        sh: age-keygen -y {{ .SOPS_AGE_KEY_FILE }}

  setup-age-key:
    internal: true
    desc: Setup age key
    deps:
      - create-age-key-in-1password
    cmd: op document get age-keys --vault homelab > {{ .SOPS_AGE_KEY_FILE }}

  create-age-key-in-1password:
    internal: true
    desc: Create age key in 1password
    deps:
      - create-homelab-vault-in-1password
    cmds:
      - task: store-age-key-in-1password

  create-homelab-vault-in-1password:
    internal: true
    desc: Create homelab vault in 1password
    cmd: op vault create homelab
    status:
      - op vault get homelab

  store-age-key-in-1password:
    internal: true
    cmd: age-keygen | op document create - --vault homelab --title age-keys --file-name {{ .SOPS_AGE_KEY_FILE | base }}
    status:
      - op document get age-keys --vault homelab | age-keygen -y
